export const PICKEDPRODUCTS = [
  {
    name: 'Among Us T-shirt',
    price: '650',
    discount: '5%',
    id: '1',
    size: 'L',
    rating: 3.5,
    color: 'white',
    description: '"Trust me I Am Not A Imposter" Half sleeve Smart T-shirt',
    images: [],
  },
  {
    name: 'T-shirt',
    price: '400',
    discount: 0,
    id: '2',
    description: '',
    images: [],
  },
  {
    name: 'T-shirt',
    price: '400',
    discount: 0,
    id: '3',
    description: '',
    images: [],
  },
  {
    name: 'T-shirt',
    price: '400',
    discount: 0,
    id: '4',
    description: '',
    images: [],
  },
  {
    name: 'T-shirt',
    price: '400',
    discount: 0,
    id: '5',
    description: '',
    images: [],
  },
];
